spring.application.name=stallsspringboot
spring.datasource.url=jdbc:mysql://localhost:3306/stallsspringboot?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
razorpay.key.id=rzp_test_SKpsVSA2lU5EEg
razorpay.key.secret=H4DW8KNrNAmCw3rkSSX2hHtH
upload.dir=uploads/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adumangalivenkatesh@gmail.com
spring.mail.password=lnbl tsux tebg qhic

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true